export enum Errors {
  BAD_REQUEST = 1,
  RESOURCE_NOT_FOUND = 2,
  ROUTE_NOT_FOUND = 3,
  UNAUTHORIZED = 4,
  FORBIDDEN = 5,
  USER_ALREADY_EXISTS = 6,
  INTERNAL_SERVER_ERROR = 7,
  MONGO_CREATION_FAILED = 8,
  INVALID_CREDENTIALS = 9,
}
